export const DEFAULT_EXPENSE_CATEGORIES: { name: string; description: string }[] = [
  { name: "Stock Restock", description: "Replenishing goods held for resale" },
  { name: "Raw Materials", description: "Unprocessed inputs used in production" },
  { name: "Wholesale Purchases", description: "Bulk goods bought for resale" },
  { name: "Salaries & Wages", description: "Staff pay, allowances and bonuses" },
  { name: "Staff Feeding", description: "Meals and refreshments for staff" },
  { name: "Staff Transport Allowance", description: "Commute support paid to staff" },
  { name: "Rent", description: "Shop, office or warehouse rent" },
  { name: "Electricity", description: "PHCN / disco power bills" },
  {
    name: "Generator Fuel & Maintenance",
    description: "Petrol, diesel, servicing and repairs for generators",
  },
  { name: "Gas & Cooking", description: "Cooking gas and related costs" },
  { name: "Water", description: "Water supply and borehole costs" },
  { name: "Internet & Data", description: "Browsing data, MiFi and ISP subscriptions" },
  { name: "Airtime & Calls", description: "Phone credit for business calls" },
  { name: "Transport & Logistics", description: "Movement of people and goods within town" },
  { name: "Delivery & Dispatch", description: "Rider fees and waybill charges to customers" },
  { name: "Packaging Materials", description: "Nylons, boxes, bottles, labels and bags" },
  { name: "Marketing & Ads", description: "Online ads, flyers, banners and promos" },
  { name: "Photography & Content", description: "Product shoots and content creation" },
  { name: "Printing & Stationery", description: "Receipts, invoices, paper and office supplies" },
  { name: "Cleaning & Sanitation", description: "Cleaning supplies and waste disposal" },
  { name: "Repairs & Maintenance", description: "Fixing shop, tools and machines" },
  { name: "Equipment Purchase", description: "Machines, tools and appliances" },
  { name: "Furniture & Fittings", description: "Shelves, chairs, tables and decor" },
  { name: "Bank Charges", description: "COT, maintenance and SMS alert fees" },
  { name: "POS Charges", description: "Point-of-sale transaction deductions" },
  { name: "Mobile Transfer Fees", description: "Inter-bank and USSD transfer charges" },
  { name: "Loan Repayment", description: "Repaying borrowed business funds" },
  { name: "Savings & Contributions", description: "Ajo, esusu and cooperative contributions" },
  { name: "Taxes & Levies", description: "Government taxes, market and council levies" },
  { name: "Licenses & Permits", description: "Business registration and operating permits" },
  { name: "Insurance", description: "Shop, goods and vehicle cover" },
  { name: "Legal & Professional Fees", description: "Lawyers and other professional services" },
  { name: "Accounting & Bookkeeping", description: "Accountants and record-keeping costs" },
  { name: "Consulting Fees", description: "Business advice and expert help" },
  { name: "Subscriptions & Software", description: "Apps, tools and service subscriptions" },
  { name: "Website & Domain", description: "Hosting, domain and site upkeep" },
  { name: "Security", description: "Guards, vigilante dues and security gadgets" },
  { name: "Staff Training", description: "Courses and skill upgrades for staff" },
  { name: "Uniforms & Workwear", description: "Branded clothing and protective gear" },
  { name: "Events & Promotions", description: "Trade fairs, launches and activations" },
  { name: "Commissions Paid", description: "Cut paid to agents and marketers" },
  { name: "Discounts Given", description: "Price cuts granted to customers" },
  { name: "Refunds & Returns", description: "Money returned for rejected goods" },
  { name: "Bad Debt Written Off", description: "Customer debts confirmed unrecoverable" },
  { name: "Import & Clearing Costs", description: "Customs, clearing and freight on imports" },
  { name: "Storage & Warehousing", description: "Paid space for keeping goods" },
  { name: "Personal Drawings", description: "Owner withdrawals for personal use" },
  { name: "Emergency & Contingency", description: "Unexpected urgent spending" },
  { name: "Cost of Goods Sold", description: "Direct cost of items sold" },
  { name: "Miscellaneous", description: "Small expenses that fit no other category" },
];
