-- Follow-up to 0022.
--
-- That migration was generated by scanning CREATE TABLE bodies, which missed
-- "order_item"."discount_kobo" because 0011 added it with ALTER TABLE ADD COLUMN
-- rather than in the table definition. The drizzle schema already called this
-- column discount_minor, so code and database disagreed until this ran.
ALTER TABLE "order_item" RENAME COLUMN "discount_kobo" TO "discount_minor";
